Views
rpire/blog-app pull request #5
Opened 2021-12-07 22:26 UTC by rpire

## Changes made:
- Linked Model and Controller methods.
- Added a message to the default layout to display in all views.
- Made views display the correct information by refactoring the views files.

2021-12-07 22:55 UTC, oxenprogrammer requested changes
Hi @rpire, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-07 22:55 UTC, oxenprogrammer commented on app/views/users/index.html.erb
> +</ul>
**Changes Required**
- [ ] Clicking on each user takes you to their show page. Let us please add this link

2021-12-08 14:59 UTC, rpire commented on app/views/users/index.html.erb
> +</ul>
Changes applied.

2021-12-08 15:00 UTC, rpire commented
Hello, @oxenprogrammer 👋

Thank you for reviewing my work! You are right. Adding links makes navigation through the app a lot easier. I didn't think of adding them before because I didn't see them in the requirements, but I'm glad you have brought them up. 🤓

Thanks again for the review. The required changes are complete and, I will proceed to request another review. 🔎

Cheers and Happy coding to you too! 🐱‍💻

2021-12-08 15:28 UTC, oloomoses approved these changes
Hi @rpire, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-08 15:51 UTC, rpire commented
Hello, @oloomoses 🙌

Thank you for reviewing my work. I will proceed to merge these changes into the `dev` branch 🚀

Cheers and Happy coding to you too. 🐱‍💻

2021-12-08 15:51 UTC, merged